### ISSUE TITLE
sorting algorithms research

### ISSUE THREAD

**Issue by praneetha1595** [nd6023/202Project#7]

**Comment by arshbhatti8** [comment]
**Sorting Algorithm: Bubble sort**
I chose bubble sort for my research of sorting algorithms this week because Bubble sort is a simple sorting algorithm. It can be a like a starting base for people new to the Computer Science world. Since our model of teaching the algorithms was also going to be in an incremental one (based on increasing complexity), I chose to research on one of the most easiest ones. 
This algorithm is not suitable for large data sets. The reason for that is that its average and worst case complexity are of the Order (n2):where n is the number of items. Bubble sort algorithm is comparison based algorithm. Each pair of adjacent elements in a data set is compared and elements are swapped if they are not in order. 
The translation of the same thing in code would be like assuming  that the list is an array of n elements. Then, we use the swap function. The values are swapped (of given array elements). And this is how it proceeds to get the list of elements sorted. We could have huge signs with numbers written on them and we could explain the bubble sort algorithm to our test group of people. They would then perform the actual sort with people holding those signs. Another idea I have is to replace the signs with actual objects with their weights written on them. The third idea is to replace the signs with images of objects and animals or anything that can be easily distinguished from the other items on the list, according to their weights. The people in the test group would then perform the sort on those items.
